# Generated by Django 3.2.23 on 2023-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0189_merge_20230929_0857"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="recalculate_discounted_price",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE product_product
            ALTER COLUMN recalculate_discounted_price
            SET DEFAULT false;
            """,
            migrations.RunSQL.noop,
        ),
    ]
